Use AdventureWorksDW2017;

SELECT * FROM DimEmployee;

-- employee count in each department using group by
SELECT DEPARTMENTNAME,COUNT(FirstName) AS EmployeeCount FROM DimEmployee
GROUP BY DepartmentName
ORDER BY COUNT(FIRSTNAME) DESC;

--Top 10 employee count
SELECT top 10 DEPARTMENTNAME,COUNT(FirstName) AS EmployeeCount FROM DimEmployee
GROUP BY DepartmentName
ORDER BY COUNT(FIRSTNAME) DESC;


--Departmentwise Male female count using group by
SELECT DEPARTMENTNAME,Gender , COUNT(EmployeeKey) AS EmployeeCount FROM DimEmployee
GROUP BY DepartmentName,Gender
ORDER BY DepartmentName DESC;

--Question : Display Firstname and their department wise avg salary and vacation hours

SELECT firstname,DEPARTMENTNAME , COUNT(EmployeeKey) AS EmployeeCount,AVG(vacationhours) FROM DimEmployee
GROUP BY DepartmentName,FirstName
ORDER BY DepartmentName DESC;
--Above statement is not giving the department wise count and vacation hours because here group is formed by the combination of firstname and department
--To tackle this problem we can use partition by

SELECT FIRSTNAME,LASTNAME,DEPARTMENTNAME , COUNT(employeekey) OVER(PARTITION BY DEPARTMENTNAME) as EMP_Count, AVG(VACATIONHOURS) OVER(PARTITION BY DEPARTMENTNAME)
AS AVH FROM DimEmployee
ORDER BY AVH  DESC,VacationHours DESC;


SELECT  FIRSTNAME,LASTNAME,DEPARTMENTNAME , VACATIONHOURS , AVG(VACATIONHOURS) OVER(PARTITION BY DEPARTMENTNAME)
AS AVH , DENSE_RANK()  OVER(PARTITION BY DEPARTMENTNAME ORDER BY VACATIONHOURS DESC)
AS RANKS FROM DimEmployee
ORDER BY AVH  DESC,VacationHours DESC;

--TO GET TOP 3 VACATION HOURS IN EACH DEPARTMENT 
/*
SELECT  FIRSTNAME,LASTNAME,DEPARTMENTNAME , VACATIONHOURS , AVG(VACATIONHOURS) OVER(PARTITION BY DEPARTMENTNAME)
AS AVH , DENSE_RANK()  OVER(PARTITION BY DEPARTMENTNAME ORDER BY VACATIONHOURS DESC)
AS RANKS FROM DimEmployee
WHERE RANKS < 4 --ANALYTICS FUNCTIONS ARE COMPUTED AFTER "WHERE" CLAUSE SO RANKS COLUMN WILL NOT BE HERE SO WE HAVE TO USE SUBQUERY 
WHICH WILL GET EXECUTED BEFORE "WHERE" STATEMENT
ORDER BY AVH  DESC,VacationHours DESC;
*/

/*SELECT  FIRSTNAME , LASTNAME , DEPARTMENTNAME , VACATIONHOURS , AVH , RANKS  FROM 
	(SELECT  FIRSTNAME,LASTNAME,DEPARTMENTNAME , VACATIONHOURS , AVG(VACATIONHOURS) OVER(PARTITION BY DEPARTMENTNAME)
	AS AVH , DENSE_RANK()  OVER(PARTITION BY DEPARTMENTNAME ORDER BY VACATIONHOURS DESC)
	AS RANKS FROM DimEmployee)
WHERE RANKS < 4 
*/
--ORDER BY AVH  DESC,VacationHours DESC;

SELECT FIRSTNAME,LASTNAME,DepartmentName,VacationHours,Avg_Vacation_Hrs,RANKS FROM
														(SELECT  FIRSTNAME,LASTNAME,DEPARTMENTNAME , VACATIONHOURS , 
														AVG(VACATIONHOURS) OVER(PARTITION BY DEPARTMENTNAME) AS Avg_Vacation_Hrs , 
														DENSE_RANK()  OVER(PARTITION BY DEPARTMENTNAME ORDER BY VACATIONHOURS DESC)
														AS RANKS FROM DimEmployee ) A --If we dont write A it will give error
WHERE A.RANKS < 4;


